[build]
  functions = "netlify/functions"
  command = "npm install && mkdir -p dist && cp -r public/* dist/ && cp index.html script.js dist/ && cp -r modules dist/"
  publish = "dist"

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"
